# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME

term xterm-256color

enable_audio_bell       no
hide_window_decorations yes

font_family      BlexMono Nerd Font Mono Light
bold_font        BlexMono Nerd Font Mono Bold
italic_font      BlexMono Nerd Font Mono Light Italic
bold_italic_font BlexMono Nerd Font Mono Bold Italic
font_size        18
modify_font      cell_width 89%

dynamic_background_opacity yes
shell_integration          no-cursor
cursor                     #ffffff
cursor_text_color          #000000
cursor_shape               block
cursor_shape_unfocused     hollow
cursor_blink_interval      0
mouse_hide_wait            -1
background_opacity         0.90

remember_window_size  no
initial_window_width  144c
initial_window_height 38c
placement_strategy    center
window_border_width   0.5pt

tab_bar_edge          top
tab_bar_style         powerline
tab_powerline_style   angled
active_tab_background #FFAF00
active_tab_foreground #000000

selection_background #FFAF00
selection_foreground #FFFFFF

allow_remote_control    yes
remote_control_password "password"
