-- ~/.config/nvim/after/plugin/snippet.lua

-- local expand = function()
-- 	local line = vim.fn.getline(".")
-- 	local candidate = vim.fn.matchstr(line, "[a-zA-Z0-9]\\+")
-- 	return candidate
-- end
--
-- vim.keymap.set({ 'i', 's' }, '<C-D>', function() return expand() end,
-- 	-- function()
-- 	-- 	if vim.snippet.active({ direction = 1 }) then
-- 	-- 		return '<Cmd>lua vim.snippet.jump(1)<CR>'
-- 	-- 	else
-- 	-- 		return '<C-D>'
-- 	-- 	end
-- 	-- end,
-- 	{ desc = '...', expr = true, silent = true }
-- )
--
-- vim.keymap.set({ 'i', 's' }, '<C-A>', function()
-- 	if vim.snippet.active({ direction = -1 }) then
-- 		return '<Cmd>lua vim.snippet.jump(-1)<CR>'
-- 	else
-- 		return '<C-D>'
-- 	end
-- end, { desc = '...', expr = true, silent = true })
