-- ~/.config/nvim/lua/completion-item-icons.lua

return {
	Text          = "𝐓",
	Method        = "",
	Function      = "𝒇",
	Constructor   = "",
	Field         = "",
	Variable      = "",
	Class         = "",
	Interface     = "",
	Module        = "𝕄",
	Property      = "",
	Unit          = "",
	Value         = "",
	Enum          = "",
	Keyword       = "",
	Snippet       = "✂︎",
	Color         = "",
	File          = "",
	Reference     = "",
	Folder        = "",
	EnumMember    = "",
	Constant      = "",
	Struct        = "",
	Event         = "",
	Operator      = "÷",
	TypeParameter = "𝕋",
}
