-- ~/.config/nvim/lua/lsp_icons.lua

return {
	Text          = '𝐓',
	Method        = '',
	Function      = '𝒇',
	Constructor   = '',
	Field         = '',
	Variable      = '►',
	Class         = '',
	Interface     = '',
	Module        = '',
	Property      = '',
	Unit          = '',
	Value         = '',
	Enum          = '',
	Keyword       = '',
	Snippet       = '✂︎',
	Color         = '',
	File          = '',
	Reference     = '',
	Folder        = '',
	EnumMember    = '',
	Constant      = '',
	Struct        = '',
	Event         = '',
	Operator      = '÷',
	TypeParameter = '𝕋',
}
