#!/bin/bash

echo "$(basename $0): use 'rig' instead." >&2
exit 1

r_path="/Library/Frameworks/R.framework/Versions"

pushd "$r_path" > /dev/null
[[ "$1" == "" ]] && {
	ls -lAhG
	popd > /dev/null
	exit 0
}

unlink Current
ln -s "$1" Current
popd > /dev/null
exit 0
