[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
cursor = "0xffffff"
text = "0x000000"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[colors.selection]
background = "0xFFAF00"
text = "0xffffff"

[font]
size = 18

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "IBM Plex Mono"
style = "Light"

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.italic]
family = "IBM Plex Mono"
style = "Light Italic"

[font.offset]
x = -1
y = -3

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_title = true
opacity = 0.90

[window.dimensions]
columns = 155
lines = 42

[window.padding]
x = 0
y = 0

[window.position]
x = 22
y = 35
